/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ape({ config ,...props }) {
  const { nodes, materials } = useGLTF('/ape.glb')
  return (
    <group {...props} dispose={null} rotation-y={-Math.PI/2} scale={1.3}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_e168d838-12c2-4b49-bc5b-ce000a51d551'].geometry}
        material={materials['tripo_mat_e168d838-12c2-4b49-bc5b-ce000a51d551']}
      >
        <meshStandardMaterial color={config.body}/>
        </mesh>
    </group>
  )
}

useGLTF.preload('/ape.glb')